apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-api-key
  namespace: demo
spec:
  refreshInterval: "1m" # refesh the secret every minute
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dev-api-credentials
  data:
  - secretKey: api-key
    remoteRef:
      key: "dev"
      property: "api-key"
      version: "1"  # if you want to specify a version, otherwise it will get the latest version . delete this line to get the latest version